<!DOCTYPE html>
<html>
<right>


<head>
<title>COARSE GROUPING</title>
</head>
<div style="width: 100%; ">
<span style="font-size:30px;float: right;cursor:pointer" onclick="openNav()">&#9776; open</span>

<img src="StudyPortals-Logo.png" alt="Mountain View" style="width:300px;height:70px;">



<style>
body {
    margin: 0;
    font-family: 'Lato', sans-serif;
}

.overlay {
    height: 0%;
    width: 100%;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.9);
    overflow-y: hidden;
    transition: 0.5s;
}

.overlay-content {
    position: relative;
    top: 25%;
    width: 100%;
    text-align: center;
    margin-top: 30px;
}

.overlay a {
    padding: 8px;
    text-decoration: none;
    font-size: 36px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.overlay a:hover, .overlay a:focus {
    color: #f1f1f1;
}

.overlay .closebtn {
    position: absolute;
    top: 20px;
    right: 45px;
    font-size: 60px;
}

@media screen and (max-height: 450px) {
  .overlay {overflow-y: auto;}
  .overlay a {font-size: 20px}
  .overlay .closebtn {
    font-size: 40px;
    top: 15px;
    right: 35px;
  }
}
</style>
</head>
<body>

<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
    <a href="http://localhost/project/homepage.php">HOME</a>
    <a href="http://localhost/project/offices.php">OFFICES</a> 
    <a href="#">LOG IN</a>
    <a href="http://localhost/project/suggestion.php">CONTACT US</a>
    
  </div>
</div>




<script>
function openNav() {
    document.getElementById("myNav").style.height = "100%";
}

function closeNav() {
    document.getElementById("myNav").style.height = "0%";
}
</script>
















<head>
<style>
button.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

button.accordion.active, button.accordion:hover {
    background-color: #ddd;
}

button.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}

button.accordion.active:after {
    content: "\2212";
}

div.panel {
    padding: 0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>


<button class="accordion">AGRICULTURAL SCIENCES</button>
<div class="panel">

  <p>BACHELOR OF SCIENCE (AGRICULTURE)</p> 	
  <p>BACHELOR OF SCIENCE IN AGRICULTURE</p>
  <p>BACHELOR OF SCIENCE (RANGE MANAGEMENT)</p>
  <p>BACHELOR OF EDUCATION SCIENCE (AGRICULTURE)</p>
  <p>BACHELOR OF SCIENCE (MANAGEMENT OF AGRO-ECOSYSTEM AND ENVIRONMENT)</p>
 <p> BACHELOR OF SCIENCE (HORTICULTURAL SCIENCE AND MANAGEMENT)</p>
 <p> BACHELOR OF SCIENCE (HORTICULTURE, WITH IT)</p>
  <p>BACHELOR OF SCIENCE (HORTICULTURE)</p>
  <p>BACHELOR OF SCIENCE HORTICULTURE</p>
 <p> BACHELOR OF SCIENCE IN HORTICULTURAL SCIENCE AND MANAGEMENT</p>
 <p> BACHELOR OF SCIENCE(HORTICULTURE)</p>
  <p>BACHELOR OF SCIENCE ( AGRICULTURAL ECONOMICS AND RESOURCE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE (AGRICULTURAL ECONOMICS AND RESOURCE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE (AGRICULTURAL ECONOMICS AND RESOURCE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE (AGRICULTURAL RESOURCE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE (AGRICULTURE ECONOMICS AND RESOURCE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE IN AGRICULTURAL RESOURCE ECONOMICS AND MANAGEMENT</p>
 <p> BACHELOR OF SCIENCE IN AGRICULTURAL RESOURCE MANAGEMENT</p>
 <p> BACHELOR OF SCIENCE (AGRICULTURE AND HUMAN ECOLOGY EXTENSION)</p>
 <p> BACHELOR OF SCIENCE (ENVIRONMENTAL HORTICULTURE AND LANDSCAPING TECHNOLOGY)</p>
 <p> BACHELOR OF SCIENCE (SEED SCIENCE AND TECHNOLOGY</p>
 <p> BACHELOR OF SCIENCE IN ETHNOBOTANY</p>
 <p> BACHELOR OF SCIENCE (SOILS AND LAND USE MANAGEMENT)</p>
  <p>BACHELOR OF SCIENCE IN BIOTECHNOLOGY AND BIOSAFETY</p>
  <p>BACHELOR OF SCIENCE IN ENTOMOLOGY AND PARASITOLOGY</p>
 <p> BACHELOR OF SCIENCE (SUGAR AND AGRO PROCESSING TECHNOLOGY)</p>
<p>BACHELOR OF SCIENCE (DRY LAND, AGRICULTURE AND ENTERPRISE DEVELOPMENT)</p>
<p>BACHELOR OF SCIENCE (DRYLAND AGRICULTURE)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURE AND ENTERPRISE DEVELOPMENT)</p>
<p>BACHELOR OF SCIENCE IN AGRICULTURE AND RURAL DEVELOPMENT</p>
<p>BACHELOR OF SCIENCE (AGRICULTURAL EXTENSION EDUCATION)</p>
<p>BACHELOR OF SCIENCE AGRICULTURAL EXTENSION AND EDUCATION</p>
<p>BACHELOR OF SCIENCE IN AGRICULTURAL EDUCATION AND EXTENSION</p>
<p>BACHELOR OF SCIENCE IN AGRICULTURAL EXTENSION EDUCATION</p>
<p>BACHELOR OF EDUCATION (AGRICULTURAL EDUCATION)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURAL EDUCATION AND EXTENSION)</p>
<p>BACHELOR OF AGRICULTURAL EDUCATION AND EXTENSION</p>
<p>BACHELOR OF AGRICULTURAL EDUCATION AND EXTENSION</p>
<p>BACHELOR OF SCIENCE (AGRICULTURAL EDUCATION AND EXTENSION)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURAL EDUCATION AND EXTENSION)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURAL EXTENSION AND EDUCATION)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURE EDUCATION AND EXTENSION)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURE EDUCATION AND EXTENSION, WITH IT)</p>
<p>BACHELOR OF SCIENCE (AGRICULTURE EDUCATION AND EXTENSION)</p>
<p>BACHELOR OF SCIENCE IN AGRICULTURAL EDUCATION AND EXTENSION</p>
<p>BACHELOR OF SCIENCE (CROP PROTECTION)</p>

	<p>BACHELOR OF SCIENCE (CROP IMPROVEMENT AND PROTECTION)</p>
	<p>BACHELOR OF SCIENCE (LEATHER TECHNOLOGY)</p>
	<p>BACHELOR OF SCIENCE IN LEATHER TECHNOLOGY</p>
	<p>BACHELOR OF SCIENCE (BOTANY)</p>
	<p>BACHELOR OF SCIENCE (ZOOLOGY)</p>
	<p>BACHELOR OF SCIENCE (SOIL SCIENCE, WITH IT)</p>
	<p>BACHELOR OF SCIENCE (SOIL SCIENCE)</p>
	<p>VBACHELOR OF SCIENCE (NATURAL PRODUCTS)</p>
	<p>BACHELOR OF SCIENCE (AGRICULTURAL BIOTECHNOLOGY)</p>
	<p>BACHELOR OF SCIENCE (AGRICULTURE AND BIOTECHNOLOGY)</p>
	<p>BACHELOR OF SCIENCE (AGRICULTURE AND BIOTECHNOLOGY)</p>
	<p>BACHELOR OF SCIENCE (SUGAR TECHNOLOGY)</p>
	<p>DIPLOMA IN AGRICULTURE</p>
	<p>DIPLOMA IN GENERAL AGRICULTURE</p>
	<p>DIPLOMA IN AGRICULTURAL ENGINEERING</p>
	<p>DIPLOMA IN AGRICULTURE ENGINEERING</p>
	<p>DIPLOMA IN HORTICULTURE</p>
</div>




<button class="accordion">HEALTH SCIENCES</button>
<div class="panel">

   <p>BACHELOR OF DENTAL SURGERY </p>	
   <p>BACHELOR OF PHARMACY 	</p>
    <p>BACHELOR OF MEDICINE AND BACHELOR OF SURGERY </p>	
	<p>BACHELOR OF MEDICINE AND BACHELOR OF SURGERY</p> 
	<p>BACHELOR OF MEDICINE AND BACHELOR OF SURGERY </p>	
	<p> BACHELOR OF MEDICINE AND BACHELOR OF SURGERY </p>
	<p> BACHELOR OF MEDICINE AND BACHELOR OF SURGERY </p> 	
	<p> BACHELOR OF SCIENCE (NURSING, WITH IT) </p>	
	<p> BACHELOR OF SCIENCE (NURSING) </p>	
	<p> BACHELOR OF SCIENCE IN NURSING </p>	
	<p> BACHELOR OF SCIENCE IN NURSING SCIENCE </p>	
	<p> BACHELOR OF SCIENCE (GENOMIC SCIENCES) </p>	
	<p> BACHELOR OF SCIENCE IN ORAL HEALTH</p> 	
	<p> BACHELOR OF SCIENCE (MEDICAL SOCIAL WORK) </p>	
	<p> BACHELOR OF SCIENCE CLINICAL MEDICINE </p>	
	<p> BACHELOR OF RADIOGRAPHY </p>	
	<p> BACHELOR OF POPULATION HEALTH </p>	
	<p> BACHELOR OF SCIENCE (POPULATION HEALTH)</p> 	
	<p> BACHELOR OF SCIENCE IN MIDWIFERY </p>	
	<p> BACHELOR OF SCIENCE (PUBLIC HEALTH, WITH IT) </p>	
	<p> BACHELOR OF SCIENCE (PUBLIC HEALTH) </p>	
	<p> BACHELOR OF SCIENCE IN PUBLIC HEALTH </p>	
	<p> BACHELOR OF TECHNOLOGY (COMMUNITY AND PUBLIC HEALTH)</p> 	
	<p> BACHELOR OF SCIENCE (FORENSIC BIOLOGY) </p>	
	<p> DIPLOMA IN CLINICAL MEDICINE </p>	
	<p> DIPLOMA IN PHYSIOTHERAPY </p>	
	<p> DIPLOMA IN PHARMACEUTICAL TECHNOLOGY </p>	
	<p> DIPLOMA IN OPTOMETRY </p>	
	<p> DIPLOMA IN MEDICAL BIO-TECHNOLOGY </p>	
	<p> DIPLOMA IN KENYA REGISTERED NURSE (KRN)</p> 	
	<p> DIPLOMA IN COMMUNITY HEALTH NURSING </p>	
	<p> DIPLOMA IN REGISTERED NURSING, MENTAL HEALTH AND PSYCHIATRY </p>	
	<p> DIPLOMA IN MEDICAL IMAGING SCIENCE </p>	
	<p> DIPLOMA IN COMMUNITY ORAL HEALTH </p>	
	<p> DIPLOMA IN DENTAL TECHNOLOGY</p> 	
	<p> DIPLOMA IN PHARMACY </p>	
	<p> DIPLOMA IN ORTHOPAEDIC TECHNOLOGY</p> 	
	<p> DIPLOMA IN COMMUNITY HEALTH AND HIV MANAGEMENT</p> 	

</div>

<button class="accordion">HOME ECONOMICS</button>
<div class="panel">
  
 	<p>BACHELOR OF ARTS (TEXTILES, APPAREL DESIGN AND FASHION MERCHANDISING, WITH IT)</p> 	
	<p>BACHELOR OF SCIENCE (APPAREL & FASHION TECHNOLOGY) </p>	
	<p>BACHELOR OF SCIENCE (CLOTHING TEXTILE & INTERIOR DESIGN) </p>	
	<p>BACHELOR OF SCIENCE (FASHION DESIGN & MARKETING) </p>	
	<p>BACHELOR OF SCIENCE (FASHION DESIGN AND TEXTILE TECHNOLOGY)</p> 	
	<p>BACHELOR OF SCIENCE IN FASHION DESIGN AND MARKETING 	
	<p>DIPLOMA IN CLOTHING & TEXTILE </p>	
	<p>DIPLOMA IN CLOTHING TECHNOLOGY </p>	
	<p>DIPLOMA IN FASHION & GARMENT MAKING </p>	
	<p>DIPLOMA IN FASHION DESIGN & CLOTHING </p>	
	<p>DIPLOMA IN FASHION DESIGN & CLOTHING TECHNOLOGY </p>	
	<p>DIPLOMA IN FASHION DESIGN & GARMENT MAKING </p>	
	<p>DIPLOMA IN FASHION DESIGN & GARMENT MAKING TECHNOLOGY</p> 	
	<p>DIPLOMA IN FASHION DESIGN AND CLOTHING 	</p>
	<p>DIPLOMA IN FASHION DESIGN AND GARMENT MAKING </p>	
	<p>DIPLOMA IN FASHION DESIGN AND GARMENT MAKING TECHNOLOGY </p>	
	<p>Diploma in Fasion Design and Garment Making Technology</p>


</div>
<button class="accordion">HOSPITALITY AND TOURISM MANAGEMENT</button>
<div class="panel">
  <p>BACHELOR OF HOSPITALITY AND TOURISM MANAGEMENT </p>	
	<p>BACHELOR OF SCIENCE (HOSPITALITY & TOURISM MANAGEMENT)</p> 	
	<p>BACHELOR OF SCIENCE (HOSPITALITY AND TOURISM MANAGEMENT)</p> 	
	<p>BACHELOR OF SUSTAINABLE TOURISM AND HOSPITALITY MANAGEMENT</p> 	
	<p>BACHELOR OF HOTEL & HOSPITALITY MANAGEMENT </p>	
	<p>BACHELOR OF HOTEL AND HOSPITALITY MANAGEMENT </p>	
	<p>BACHELOR OF HOTELS AND HOSPITALITY MANAGEMENT </p>	
	<p>BACHELOR OF TOURISM & HOTEL MANAGEMENT 	</p>
	<p>BACHELOR OF ECO-TOURISM AND HOSPITALITY MANAGEMENT</p> 	
	<p>BACHELOR OF SCIENCE (ECO-TOURISM, HOTEL AND INSTITUTION MANAGEMENT, WITH IT) </p>	
	<p>BACHELOR OF SCIENCE (ECOTOURISM & HOSPITALITY MANAGEMENT) </p>	
	<p>BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT </p>	
	<p>BACHELOR OF TECHNOLOGY IN HOTEL & HOSPITALITY MANAGEMENT </p>	
	<p>BACHELOR OF TECHNOLOGY (HOTEL AND RESTAURANT MANAGEMENT) </p>	
	<p>BACHELOR OF CATERING & HOTEL MANAGEMENT 	</p>
	<p>BACHELOR OF CATERING AND HOTEL MANAGEMENT </p>	
	<p>BACHELOR OF HOSPITALITY MANAGEMENT 	</p>
	<p>BACHELOR OF SCIENCE IN HOTEL AND RESTAURANT MANAGEMENT </p>	
	<p>BACHELOR OF SCIENCE (HOSPITALITY MANAGEMENT) </p>	
	<p>DIPLOMA IN HOUSEKEEPING MANAGEMENT </p>	
	<p>DIPLOMA IN TOUR GUIDING 	</p>
	<p>DIPLOMA IN TOURISM AND HOSPITALITY MANAGEMENT </p>	
	<p>DIPLOMA IN TOURISM MANAGEMENT </p>	
	<p>DIPLOMA IN TRAVEL,TOURISM & HOSPITALITY 	</p>
	<p>DIPLOMA IN HOTEL AND INSTITUTIONAL MANAGEMENT </p>	

</div>
<button class="accordion">HUMANITIES AND SOCIAL SCIENCES</button>
<div class="panel">
  
    <p>BACHELOR OF ARTS 	
	<p>BACHELOR OF ARTS (WITH IT) 	
	<p>BACHELOR OF ARTS (DESIGN) 	
	<p>BACHELOR OF ARTS (ANTHROPOLOGY) 	
	<p>BACHELOR OF ARTS IN ANTHROPOLOGY 	
	<p>BACHELOR OF ARTS (SOCIAL WORK) 	
	<p>BACHELOR OF ARTS(SOCIAL WORK) 	
	<p>BACHELOR OF SOCIAL WORK 	
	<p>BACHELOR OF SCIENCE (INFORMATION SCIENCE) 	
	<p>BACHELOR OF SCIENCE (INFORMATION SCIENCES AND KNOWLEDGE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (INFORMATION SCIENCES) 	
	<p>BACHELOR OF SCIENCE IN INFORMATION SCIENCE 	
	<p>BACHELOR OF SCIENCE IN INFORMATION SCIENCES 	
	<p>BACHELOR OF ARTS (PUBLIC ADMINISTRATION) 	
	<p>BACHELOR OF MUSIC 	
	<p>BACHELOR OF ARTS (MUSIC, WITH IT) 	
	<p>BACHELOR OF ARTS (MUSIC) 	
	<p>BACHELOR OF ARTS (PLANNING) 	
	<p>BACHELOR OF ARTS (FRENCH) 	
	<p>BACHELOR OF EDUCATION (FRENCH, WITH IT) 	
	<p>BACHELOR OF ARTS (GERMAN) 	
	<p>BACHELOR OF EDUCATION (ARTS) GERMAN 	
	<p>BACHELOR OF ARTS (COMMUNITY DEVELOPMENT) 	
	<p>BACHELOR OF ARTS COMMUNITY DEVELOPMENT 	
	<p>BACHELOR OF ARTS IN COMMUNITY DEVELOPMENT 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (COMMUNITY DEVELOPMENT) 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES AND COMMUNITY DEVELOPMENT 	
	<p>BACHELOR OF ARTS (PSYCHOLOGY) 	
	<p>BACHELOR OF PSYCHOLOGY 	
	<p>BACHELOR OF PSYCHOLOGY ( WITH IT) 	
	<p>BACHELOR OF SCIENCE (COMMUNITY DEVELOPMENT) 	
	<p>BACHELOR OF SCIENCE (COMMUNITY DEVELOPMENT AND ENVIRONMENT) 	
	<p>BA in Inter-Cultural Studies 	
	<p>BACHELOR OF SCIENCE (PUBLIC MANAGEMENT AND DEVELOPMENT) 	
	<p>BACHELOR OF ARTS (FRENCH, WITH IT) 	
	<p>BACHELOR OF EDUCATION (ARTS) FRENCH 	
	<p>BACHELOR OF EDUCATION (FRENCH) 	
	<p>BACHELOR OF EDUCATION ARTS (FRENCH) 	
	<p>BACHELOR OF ARTS (GEOGRAPHY) 	
	<p>BACHELOR OF ARTS IN GEOGRAPHY 	
	<p>BACHELOR OF SCIENCE (GEOGRAPHY) 	
	<p>BACHELOR OF ARTS (INTERNATIONAL RELATIONS AND DIPLOMACY ,WITH IT) 	
	<p>BACHELOR OF ARTS (INTERNATIONAL RELATIONS AND DIPLOMACY) 	
	<p>BACHELOR OF INTERNATIONAL RELATIONS & DIPLOMACY 	
	<p>BACHELOR OF ARTS IN INTERNATIONAL RELATIONS 	
	<p>BACHELOR OF ARTS (GENDER AND DEVELOPMENT STUDIES) 	
	<p>BACHELOR OF ARTS (GENDER AND DEVELOPMENT) 	
	<p>BACHELOR OF ARTS (GENDER STUDIES, WITH IT) 	
	<p>BACHELOR OF ARTS (DEVELOPMENT STUDIES, WITH IT) 	
	<p>BACHELOR OF ARTS IN DEVELOPMENT STUDIES 	
	<p>BACHELOR OF ARTS(DEVELOPMENTAL AND POLICY STUDIES) 	
	<p>BACHELOR OF DEVELOPMENT STUDIES 	
	<p>BACHELOR OF SCIENCE IN DEVELOPMENT STUDIES 	
	<p>BACHELOR OF ARTS (GENDER) 	
	<p>BACHELOR OF ARTS IN INTERNATIONAL RELATIONS AND SECURITY STUDIES 	
	<p>BACHELOR OF ARTS (INTERIOR DESIGN, WITH IT) 	
	<p>BACHELOR OF ARTS IN SUSTAINABLE HUMAN DEVELOPMENT 	
	<p>BACHELOR OF ARTS IN CHILD AND YOUTH STUDIES 	
	<p>BACHELOR OF ARTS (KISWAHILI, WITH IT) 	
	<p>BACHELOR OF ARTS (KISWAHILI) 	
	<p>BACHELOR OF ARTS IN KISWAHILI 	
	<p>BACHELOR OF ARTS (COUNSELLING PSYCHOLOGY) 	
	<p>BACHELOR OF ARTS IN COUNSELING PSYCHOLOGY 	
	<p>BACHELOR OF ARTS IN COUNSELLING PSYCHOLOGY 	
	<p>BACHELOR OF SCIENCE (COUNSELLING PSYCHOLOGY) 	
	<p>BACHELOR OF SCIENCE IN PARKS, RECREATION AND LEISURE MANAGEMENT 	
	<p>BACHELOR OF ARTS IN COUNSELING 	
	<p>BACHELOR OF ARTS IN GUIDANCE AND COUNSELLING 	
	<p>BACHELOR OF TECHNOLOGY (DESIGN) 	
	<p>BACHELOR OF SCIENCE (EXERCISE & SPORT SCIENCE) 	
	<p>BACHELOR OF SPORTS MANAGEMENT 	
	<p>BACHELOR OF SPORTS SCIENCE & MANAGEMENT 	
	<p>BACHELOR OF TECHNOLOGY IN COSMETOLOGY 	
	<p>BACHELOR OF SCIENCE (HEALTH PROMOTION AND SPORTS SCIENCE) 	
	<p>BACHELOR OF ARTS (FINE ART, WITH IT) 	
	<p>BACHELOR OF ARTS (FINE ARTS) 	
	<p>BACHELOR OF ARTS (HISTORY) 	
	<p>BACHELOR OF ARTS IN HISTORY 	
	<p>BACHELOR OF ARTS (HISTORY AND ARCHAEOLOGY, WITH IT) 	
	<p>BACHELOR OF ARTS (HISTORY AND ARCHAEOLOGY) 	
	<p>BACHELOR OF ARTS (LITERATURE, WITH IT) 	
	<p>BACHELOR OF ARTS (LITERATURE) 	
	<p>BACHELOR OF SCIENCE IN SOCIAL WORK 	
	<p>BACHELOR OF ARTS (POLITICAL SCIENCE & PUBLIC ADMINISTRATION) 	
	<p>BACHELOR OF ARTS (POLITICAL SCIENCE AND PUBLIC ADMINISTRATION) 	
	<p>BACHELOR OF ARTS IN POLITICAL SCIENCE 	
	<p>BACHELOR OF ARTS IN POLITICAL SCIENCE AND PUBLIC ADMINISTRATION 	
	<p>BACHELOR OF ARTS ( POLITICAL SCIENCE, WITH IT) 	
	<p>BACHELOR OF ARTS ( POLITICAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE (RECREATION AND SPORTS MANAGEMENT) 	
	<p>BACHELOR OF ARTS (PHILOSOPHY, WITH IT) 	
	<p>BACHELOR OF ARTS (PHILOSOPHY) 	
	<p>BACHELOR OF CONFLICT RESOLUTION AND HUMANITAIRAN ASSISTANCE 	
	<p>BACHELOR OF ARTS (PENOLOGY, CORRECTION AND ADMINISTRATION) 	
	<p>BACHELOR OF DISASTER MANAGEMENT & INTERNATIONAL DIPLOMACY 	
	<p>BACHELOR OF JUSTICE AND PEACE 	
	<p>BACHELOR OF PUBLIC POLICY AND ADMINISTRATION 	
	<p>BACHELOR OF MUSIC (TECHNOLOGY) 	
	<p>BACHELOR OF ARTS IN PEACE AND CONFLICT TRANSFORMATION 	
	<p>BACHELOR OF ARTS IN JUSTICE AND SECURITY STUDIES 	
	<p>BACHELOR OF ARTS IN PEACE STUDIES AND CONFLICT RESOLUTION 	
	<p>BACHELOR OF ARTS IN PUBLIC ADMINISTRATION 	
	<p>BACHELOR OF ARTS IN PUBLIC ADMINISTRATION AND GOVERNANCE 	
	<p>BACHELOR OF ARTS IN SECURITY STUDIES AND CRIMINOLOGY 	
	<p>BACHELOR OF ARTS IN SOCIOLOGY AND DEVELOPMENT 	
	<p>BACHELOR OF COUNSELING PSYCHOLOGY 	
	<p>BACHELOR OF SOCIAL WORK AND ADMINISTRATION 	
	<p>DIPLOMA IN COMMUNITY DEVELOPMENT AND SOCIAL WORK 	
	<p>DIPLOMA IN SOCIAL WORK & COMMUNITY DEVELOPMENT 	
	<p>DIPLOMA IN SOCIAL WORK AND COMMUNITY DEVELOPMENT 	
	<p>DIPLOMA IN SOCIAL WORK AND DEVELOPMENT 	
	<p>DIPLOMA IN SOCIAL WORK& COMMUNITY DEVELOPMENT 	
	<p>DIPLOMA IN GUIDANCE AND COUNSELLING 	
	<p>DIPLOMA IN BAKING TECHNOLOGY 	
	<p>DIPLOMA IN INFORMATION SCIENCE 	
	<p>DIPLOMA IN CLINICAL COUNSELLING PSYCHOLOGY 	
	<p>DIPLOMA IN COUNSELLING PSYCHOLOGY 	
	<p>DIPLOMA IN ART AND DESIGN 	
	<p>DIPLOMA IN LIBERAL STUDIES AND MANAGEMENT 	
	<p>DIPLOMA IN COMMUNITY DEVELOPMENT 	
	<p>DIPLOMA IN OCCUPATIONAL THERAPY 	
	<p>DIPLOMA IN LIBRARY & INFORMATION STUDIES 	
	<p>DIPLOMA IN LIBRARY AND INFORMATION STUDIES 	
	<p>DIPLOMAIN LIBRARY INFORMATION STUDIES 	
	<p>DIPLOMA IN FRONT OFFICE OPERATIONS AND CUSTOMER CARE 	
	<p>DIPLOMA IN SECRETARIAL STUDIES AND OFFICE MANAGEMENT 	
	<p>DIPLOMA IN ARCHIVES AND RECORDS MANAGEMENT 	
	<p>DIPLOMA IN COMMUNITY DEVELOPMENT AND COUNSELLING 	
	<p>DIPLOMA IN COUNTY GOVERNANCE AND ETHICS 	
	<p>DIPLOMA IN LIBRARY AND INFORMATION SCIENCE 	
	<p>DIPLOMA IN SECRETARIAL STUDIES 	
	<p>DIPLOMA IN COMPUTERIZED SECRETARIAL STUDIES 	
	<p>DIPLOMA IN INFORMATION STUDIES 	
	<p>DIPLOMA IN REFRIGERATION & AIR CONDITIONING 	
	<p>DIPLOMA IN WATER TECHNOLOGY (WATER SUPPLY OPTION) 	
	<p>DIPLOMA IN EARLY CHILDHOOD DEVELOPMENT 	


</div>
<button class="accordion">JOURNALISM AND MEDIA STUDIES</button>
<div class="panel">
  

    <p>BACHELOR OF BROADCAST JOURNALISM 	
	<p>BACHELOR OF ARTS (DRAMA AND THEATRE STUDIES, WITH IT) 	
	<p>BACHELOR OF ARTS (THEATER ARTS & FILM TECHNOLOGY) 	
	<p>BACHELOR OF JOURNALISM & MASS COMMUNICATION 	
	<p>BACHELOR OF JOURNALISM AND MASS COMMUNICATION 	
	<p>BACHELOR OF COMMUNICATION & JOURNALISM 	
	<p>BACHELOR OF SCIENCE (COMMUNICATION & JOURNALISM) 	
	<p>BACHELOR OF SCIENCE (COMMUNICATION AND JOURNALISM) 	
	<p>BACHELOR OF JOURNALISM 	
	<p>BACHELOR OF ARTS IN MASS COMMUNICATION 	
	<p>BACHELOR OF MASS COMMUNICATION 	
	<p>BACHELOR OF ARTS IN SOCIAL COMMUNICATION 	
	<p>BACHELOR OF ARTS ( KISWAHILI AND COMMUNICATION) 	
	<p>BACHELOR OF ARTS (COMMUNICATION & MEDIA TECHNOLOGY, WITH IT) 	
	<p>BACHELOR OF ARTS (COMMUNICATION & MEDIA) 	
	<p>BACHELOR OF ARTS (COMMUNICATION AND MEDIA) 	
	<p>BACHELOR OF ARTS IN KISWAHILI AND MEDIA STUDIES 	
	<p>BACHELOR OF ARTS IN PHILOSOPHY 	
	<p>BACHELOR OF ARTS IN LANGUAGE AND COMMUNICATION 	
	<p>BACHELOR OF ARTS IN LITERATURE, THEATRE AND FILM 	
	<p>BACHELOR OF TECHNOLOGY (JOURNALISM AND MASS COMMUNICATION) 	
	<p>BACHELOR OF COMMUNICATION AND MEDIA STUDIES 	
	<p>BACHELOR OF COMMUNICATION AND PUBLIC RELATIONS 	
	<p>BACHELOR OF SCIENCE (COMM. & PUBLIC RELATIONS) 	
	<p>BACHELOR OF SCIENCE (COMMUNICATION AND PUBLIC RELATIONS) 	
	<p>BACHELOR OF COMMUNICATION & PUBLIC RELATIONS 	
	<p>BACHELOR OF SCIENCE (CORPORATE COMMUNICATION AND MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (GRAPHIC, COMMUNICATION AND ADVERTISING) 	
	<p>BACHELOR OF SCIENCE (MEDIA SCIENCE) 	
	<p>BACHELOR OF APPLIED COMMUNICATION 	
	<p>BACHELOR OF SCIENCE(GRAPHIC, COMM. & ADVERTISING) 	
	<p>BACHELOR OF ARTS ( LINGUISTICS) 	
	<p>BACHELOR OF ARTS (LINGUISTIC) 	
	<p>BACHELOR OF ARTS (APPLIED LINGUISTICS) 	
	<p>BACHELOR OF ARTS (TRANSLATION AND INTERPRETATION) 	
	<p>BACHELOR OF ARTS (ENGLISH & COMMUNICATION) 	
	<p>BACHELOR OF ARTS IN ENGLISH LANGUAGE 	
	<p>BACHELOR OF ARTS IN MASS MEDIA AND COMMUNICATION 	
	<p>BACHELOR OF ARTS (SOCIOLOGY AND ANTHROPOLOGY, WITH IT) 	
	<p>BACHELOR OF ARTS IN COMMUNICATION 	
	<p>BACHELOR OF ARTS (LANGUAGE AND COMMUNICATION, WITH IT) 	
	<p>BACHELOR OF ARTS (LINGUISTICS, MEDIA AND COMMUNICATION) 	
	<p>BACHELOR OF ARTS IN HISTORY & INTERNATIONAL STUDIES 	
	<p>BACHELOR OF ARTS IN JOURNALISM 	
	<p>BACHELOR OF ARTS IN ARABIC LANGUAGE 	
	<p>BACHELOR OF FILM ANIMATION 	
	<p>DIPLOMA IN JOURNALISM & MEDIA 	
	<p>DIPLOMA IN PUBLIC RELATIONS 	
	<p>DIPLOMA IN GRAPHIC DESIGN 	
	<p>DIPLOMA IN MASS COMMUNICATION 	


</div>
<button class="accordion">LAW/LEGAL</button>
<div class="panel">
    <p>BACHELOR OF LAWS (LL.B.) 	
	<p>BACHELOR OF LAWS (LLB) 	
	<p>BACHELOR OF ARTS (CRIMINOLOGY & SECURITY STUDIES) 	
	<p>BACHELOR OF ARTS (CRIMINOLOGY AND PENOLOGY) 	
	<p>BACHELOR OF ARTS (CRIMINOLOGY AND SECURITY STUDIES) 	
	<p>BACHELOR OF ARTS (CRIMINOLOGY, WITH IT) 	
	<p>BACHELOR OF ARTS IN CRIMINAL JUSTICE 	
	<p>BACHELOR OF ARTS IN CRIMINOLOGY, CRIMINAL JUSTICE AND PUBLIC SAFETY 	
	<p>BACHELOR OF CRIMINOLOGY 	
	<p>BACHELOR OF SCIENCE (CRIMINOLOGY AND SECURITY STUDIES) 	
	<p>DIPLOMA IN HEALTH RECORDS AND INFORMATION 	
	<p>DIPLOMA IN HEALTH RECORDS AND INFORMATION TECHNOLOGY
</div>
<button class="accordion">MATHEMATICAL SCIENCES</button>
<div class="panel">
  

    <p>BACHELOR OF ACTUARIAL SCIENCE 	
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE WITH IT) 	
	<p>BACHELOR OF ACTUARIAL SCIENCE 	12
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE WITH IT) 	12
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE, WITH IT) 	12
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE) 	12
	<p>BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE 	12
	<p>BACHELOR OF SCIENCE IN MATHEMATICS ( PURE MATHEMATICS, APPLIED MATHEMATICS AND STATISTICS
	<p>BACHELOR OF ACTUARIAL SCIENCE 	
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE WITH IT) 	
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE, WITH IT) 
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS ( PURE MATHEMATICS, APPLIED MATHEMATICS AND STATISTICS)
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (ACTUARIAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS ( PURE MATHEMATICS, APPLIED MATHEMATICS AND STATISTICS)

</div>
<button class="accordion">NATURAL RESOURCE MANAGEMENT</button>
<div class="panel">
  


	<p>BACHELOR OF SCIENCE (WOOD SCIENCE AND INDUSTRIAL PROCESSES) 	
	<p>BACHELOR OF SCIENCE (WILDLIFE ENTERPRISE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (WILDLIFE ENTERPRISES & MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (WILDLIFE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN SOIL ENVIRONMENT & LAND USE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (AGROFORESTRY & RURAL DEVELOPMENT) 	
	<p>BACHELOR OF SCIENCE (FORESTRY) 	
	<p>BACHELOR OF SCIENCE (APPLIED AQUATIC SCIENCE) 	
	<p>BACHELOR OF SCIENCE (NATURAL RESOURCE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (NATURAL RESOURCES MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN NATURAL RESOURCE MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN NATURAL RESOURCES 	
	<p>BACHELOR OF SCIENCE (LAND RESOURCE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (LAND RESOURCE PLANNING & MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (EMERGENCY MANAGEMENT STUDIES) 	
	<p>BACHELOR OF SCIENCE (DISASTER MANAGEMENT AND PEACE STUDIES) 	
	<p>BACHELOR OF SCIENCE (LAND ADMINISTRATION) 	
	<p>BACHELOR OF SCIENCE IN FORESTRY ECOSYSTEM MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (WASTE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (INTEGRATED FOREST RESOURCES MANAGEMENT) 	
	<p>BACHELOR OF ARTS(SPATIAL PLANNING) 	
	<p>BACHELOR OF SCIENCE (SPATIAL MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (HYDROLOGY AND WATER RESOURCES MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (WATER RESOURCE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (FISHERIES AND AQUACULTURE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (FISHERIES AND AQUACULTURE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (FISHERIES MANAGEMENT AND AQUACULTURE TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (FISHERIES & AQUATIC SCIENCES) 	
	<p>BACHELOR OF SCIENCE IN AQUACULTURE AND FISHERIES TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN FISHERIES AND AQUACULTURE 	
	<p>BACHELOR OF SCIENCE IN FISHERIES AND AQUACULTURE 	
	<p>BACHELOR OF SCIENCE IN FISHERIES AND OCEANOGGRAPHY 	
	<p>BACHELOR OF ARTS (DISASTER MANAGEMENT, WITH IT) 	
	<p>BACHELOR OF DISASTER MANAGEMENT 	
	<p>BACHELOR OF DISASTER MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN GLOBAL HEALTH AND EMPORIATRICS 	
	<p>BACHELOR OF SCIENCE ( BIO-RESOURCES MANAGEMENT AND CONSERVATION) 	
	<p>BACHELOR OF SCIENCE (BIO-RESOURCES MANAGEMENT AND CONSERVATION) 	
	<p>BACHELOR OF SCIENCE (DISASTER RISK MANAGEMENT AND SUSTAINABLE DEVELOPMENT) 	
	<p>BACHELOR OF SCIENCE (COASTAL & MARINE RESOURCE MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (MARINE BIOLOGY & FISHERIES) 	
	<p>BACHELOR OF SCIENCE IN MARINE RESOURCE MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (UTILIZATION & SUSTAINABILITY OF ARID LANDS (USAL) 	
	<p>BACHELOR OF SCIENCE (AQUATIC RESOURCES CONSERVATION AND DEVELOPMENT, WITH IT) 	
	<p>BACHELOR OF SCIENCE ( SUSTAINABLE ENERGY & CLIMATE CHANGE SYSTEMS) 	
	<p>BACHELOR OF SCIENCE (CLIMATE CHANGE AND DEVELOPMENT, WITH IT) 	
	<p>BACHELOR OF SCIENCE (AGRONOMY, WITH IT) 	
	<p>BACHELOR OF SCIENCE (CONSERVATION BIOLOGY) 	
	<p>BACHELOR OF SCIENCE (BIOSTATISTICS) 	
	<p>DIPLOMA IN WATER RESOURCES 	
	<p>DIPLOMA IN FISHERIES AND AQUATIC SCIENCES 	
	<p>DIPLOMA IN WILDLIFE MANAGEMENT 	
	<p>DIPLOMA IN NAUTICAL SCIENCES 	
	<p>DIPLOMA IN PHOTOGRAMMETRY & REMOTE SENSING 	
	<p>DIPLOMA IN CARTOGRAPHY 	
	<p>DIPLOMA IN MAP REPRODUCTION (PRINTING) 	

</div>
<button class="accordion">PHYSICAL SCIENCES</button>
<div class="panel">
  

 	<p>BACHELOR OF SCIENCE (METEOROLOGY) 	
	<p>BACHELOR OF SCIENCE (GEOLOGY) 	
	<p>BACHELOR OF SCIENCE (ASTRONOMY AND ASTROPHYSICS) 	
	<p>BACHELOR OF SCIENCE (EARTH SCIENCE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (GEOPHYSICS) 	
	<p>BACHELOR OF TECHNOLOGY (GEOINFORMATION TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN COMMUNITY RESOURCE MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN (GEOGRAPHIC INFORMATION SYSTEMS) 	
	<p>BACHELOR OF APPLIED SCIENCE (GEO-INFORMATICS) 	
	<p>BACHELOR OF SCIENCE IN GEOLOGICAL SCIENCES AND TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (GEOPHYSICAL AND MINERALOGY) 	
	<p>BACHELOR OF SCIENCE IN GEOMATICS AND GEOSPATIAL INFORMATION SYSTEMS 	
	<p>BACHELOR OF SCIENCE (GEOMATIC ENGINEERING AND GEOSPATIAL INFORMATION SYSTEMS) 	
	<p>BACHELOR OF SCIENCE (GEOGRAPHY AND NATURAL RESOURCE MANAGEMENT, WITH IT) 	
	<p>BACHELOR OF SCIENCE (GEOSPATIAL INFORMATION SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN GEOSPATIAL INFORMATION SCIENCE AND REMOTE SENSING 	
	<p>BACHELOR OF SCIENCE (GEOSPATIAL INFORMATION SCIENCE, WITH IT) 	
	<p>BACHELOR OF TECHNOLOGY (GEOSPATIAL ENGINEERING TECHNOLOGY) 	
	<p>DIPLOMA IN ANALYTICAL CHEMISTRY 	
	<p>DIPLOMA IN LAND SURVEYING 	
	<p>DIPLOMA IN APPLIED CHEMISTRY 	


</div>
<button class="accordion">RELIGEOUS STUDIES</button>
<div class="panel">
  
    <p>BA in Biblical Studies 	
	<p>BACHELOR OF ARTS IN YOUTH MINISTRY 	
	<p>BACHELOR OF ARTS IN RELIGION 	
	<p>BACHELOR OF ARTS (RELIGION, WITH IT) 	
	<p>BACHELOR OF ARTS (THEOLOGY, WITH IT) 	
	<p>BACHELOR OF ARTS (RELIGIOUS STUDIES) 	
	<p>BACHELOR OF ARTS IN THEOLOGY 	
	<p>BACHELOR OF THEOLOGY 	
	<p>BACHELOR OF ARTS IN BIBLE AND THEOLOGY 	
	<p>BACHELOR OF ARTS IN ISLAMIC STUDIES 	
	<p>BACHELOR OF ARTS IN ISLAMIC SHARIA 	
	<p>BACHELOR OF CHRISTIAN EDUCATION 	
	<p>BACHELOR OF CHURCH MANAGEMENT AND LEADERSHIP 	
	<p>BACHELOR OF SCIENCE (DISASTER MITIGATION AND SUSTAINABLE DEVELOPMENT) 	
	<p>BACHELOR OF ARTS (SOCIOLOGY & RELIGION) 	
	<p>BACHELOR OF ARTS (SOCIOLOGY AND SOCIAL WORK) 	
	<p>BACHELOR OF ARTS (SOCIOLOGY) 	
	<p>BACHELOR OF ARTS IN SOCIOLOGY 	


</div>
<button class="accordion">BIOLOGICAL SCIENCES</button>
<div class="panel">
  

    <p>BACHELOR OF SCIENCE (BIOLOGY) 	
	<p>BACHELOR OF SCIENCE IN BIOLOGY 	
	<p>BACHELOR OF SCIENCE IN BIOLOGY ( BOTANY OR ZOOLOGY OPTION) 	
	<p>BACHELOR OF SCIENCE(BIOLOGICAL SCIENCES) 	
	<p>BACHELOR OF SCIENCE (BIOCHEMISTRY 	
	<p>BACHELOR OF SCIENCE (BIOCHEMISTRY) 	
	<p>BACHELOR OF SCIENCE IN BIOCHEMISTRY 	
	<p>BACHELOR OF SCIENCE 	
	<p>BACHELOR OF SCIENCE (B.SC) 	
	<p>BACHELOR OF SCIENCE (BASIC SCIENCE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (BSC.) 	
	<p>BSC (SCIENCE) 	
	<p>BACHELOR OF SCIENCE (MICROBIOLOGY) 	
	<p>BACHELOR OF SCIENCE IN BIOMEDICAL SCIENCE 	
	<p>BACHELOR OF SCIENCE (MEDICAL LABORATORY SCIENCE & TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (MEDICAL LABORATORY SCIENCE) 	
	<p>BACHELOR OF SCIENCE (MEDICAL LABORATORY SCIENCES, WITH IT) 	
	<p>BACHELOR OF SCIENCE (MEDICAL LABORATORY SCIENCES) 	
	<p>BACHELOR OF SCIENCE (MEDICAL LABORATORY) 	 	
	<p>BACHELOR OF SCIENCE IN MEDICAL LABORATORY SCIENCES 	
	<p>BACHELOR OF SCIENCE (BIOMEDICAL SCIENCE AND TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (BIOMEDICAL SCIENCE & TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (BIOMEDICAL SCIENCE AND TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN BIOMEDICAL SCIENCES & TECHNOLOGY	
	<p>BACHELOR OF TECHNOLOGY (SCIENCE LABORATORY TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (OCCUPATIONAL HEALTH & SAFETY) 	
	<p>BACHELOR OF SCIENCE IN LABORATORY TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (BIOTECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY (BIOTECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN COMMUNITY HEALTH EDUCATION 	
	<p>BACHELOR OF SCIENCE (MICROBIOLOGY AND BIOTECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN MICROBIOLOGY 	
	<p>BACHELOR OF TECHNOLOGY IN INDUSTRIAL MICROBIOLOGY & BIOTECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (MEDICAL MICROBIOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY (MEDICAL LABORATORY SCIENCE) 	
	<p>BACHELOR OF SCIENCE (COMMUNITY HEALTH & DEVELOPMENT) 	
	<p>BACHELOR OF SCIENCE (COMMUNITY HEALTH AND DEVELOPMENT) 	
	<p>BACHELOR OF SCIENCE IN COMMUNITY HEALTH 	
	<p>BACHELOR OF SCIENCE IN COMMUNITY HEALTH AND DEVELOPMENT 	
	<p>BACHELOR OF SCIENCE (BIOCHEMISTRY AND MOLECULAR BIOLOGY) 	
	<p>BACHELOR OF SCIENCE (CELLULAR AND MOLECULAR BIOLOGY) 	
	<p>BACHELOR OF SCIENCE (MOLECULAR & CELLULAR BIOLOGY) 	
	<p>BACHELOR OF SCIENCE IN MOLECULAR BIOLOGY AND FORENSIC TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN DENTAL TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (PARAMEDIC SCIENCE) 	
	<p>BACHELOR OF SCIENCE (PHYSIOTHERAPY) 	
	<p>BACHELOR OF TECHNOLOGY (APPLIED BIOLOGY) 	
	<p>BACHELOR OF SCIENCE (APPLIED BIOLOGY) 	
	<p>BACHELOR OF SCIENCE (MEDICAL PSYCHOLOGY) 	
	<p>BACHELOR OF PHYSIOTHERAPY 	
	<p>BACHELOR OF SCIENCE (PHYSICAL THERAPY) 	
	<p>BACHELOR OF SCIENCE (FORENSIC SCIENCE) 	
	<p>BACHELOR OF SCIENCE (MEDICAL BIOCHEMISTRY) 	
	<p>BACHELOR OF SCIENCE (MEDICAL BIOTECHNOLOGY, WITH IT) 	15
	<p>BACHELOR OF SCIENCE IN MEDICAL BIOTECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (PHARMACEUTICAL SCIENCES, WITH IT) 	
	<p>BACHELOR OF SCIENCE (OPTOMETRY AND VISION SCIENCES) 	
	<p>BACHELOR OF SCIENCE IN EPIDEMIOLOGY AND BIOSTATISTICS 	
	<p>BACHELOR OF SCIENCE (LABORATORY SCIENCES) 	
	<p>BACHELOR OF SCIENCE INDUSTRIAL BIOTECHNOLOGY 	
	<p>DIPLOMA IN APPLIED BIOLOGY 	
	<p>DIPLOMA IN INDUSTRIAL MICROBIOLOGY 	
	<p>DIPLOMA IN MEDICAL LABORATORY SCIENCE 	
	<p>DIPLOMA IN MEDICAL LABORATORY SCIENCES 	
	<p>DIPLOMA IN INDUSTRIAL MICROBIOLOGY & BIOTECHNOLOGY 	
	<p>DIPLOMA IN MEDICAL LABORATORY TECHNOLOGY 	
	<p>DIPLOMA IN SCIENCE LABORATORY TECHNOLOGY 	
	<p>DIPLOMA IN OPTICAL TECHNOLOGY 	



</div>
<button class="accordion">VETINARY/ANIMAL SCIENCES</button>
<div class="panel">
  

    <p>BACHELOR OF VETERINARY MEDICINE 	
	<p>BACHELOR OF SCIENCE (ANIMAL HEALTH, PRODUCTION & PROCESSING) 	
	<p>BACHELOR OF SCIENCE IN ANIMAL HEALTH AND PRODUCTION 	
	<p>BACHELOR OF SCIENCE IN ANIMAL PRODUCTION 	
	<p>BACHELOR OF SCIENCE (ANIMAL PRODUCTION & HEALTH MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (ANIMAL SCIENCE & MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (ANIMAL SCIENCE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (ANIMAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN ANIMAL SCIENCE & TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (ANIMAL HEALTH & PRODUCTION) 	
	<p>BACHELOR OF SCIENCE (ANIMAL HEALTH AND PRODUCTION) 	
	<p>BACHELOR OF SCIENCE (DAIRY TECHNOLOGY & MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN APPLIED ANIMAL LABORATORY SCIENCE 	
	<p>BACHELOR OF SCIENCE (DRYLAND ANIMAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN ANIMAL HEALTH MANAGEMENT 	



</div>
<button class="accordion">BUILDING AND CONSTRUCTION SCIENCES</button>
<div class="panel">
  

	<p>BACHELOR OF ARCHITECTURAL STUDIES/BACHELOR OF ARCHITECTURE 	
	<p>BACHELOR OF ARCHITECTURE 	
	<p>BACHELOR OF QUANTITY SURVEYING 	
	<p>BACHELOR OF SCIENCE (QUANTITY SURVEYING) 	
	<p>BACHELOR OF CONSTRUCTION MANAGEMENT 	
	<p>BACHELOR OF URBAN AND REGIONAL PLANNING 	
	<p>BACHELOR OF LANDSCAPE ARCHITECTURE 	
	<p>BACHELOR OF TECHNOLOGY (BUILDING CONSTRUCTION) 	
	<p>BACHELOR OF THE BUILT ENVIRONMENT (URBAN AND REGIONAL PLANNING) 	
	<p>BACHELOR OF TECHNOLOGY (SURVEYING TECHNOLOGY) 	
	<p>BACHELOR OF ARCHITECTURAL TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (URBAN DESIGN AND DEVELOPMENT) 	
	<p>BACHELOR OF THE BUILT ENVIRONMENT (CONSTRUCTION MANAGEMENT) 	
	<p>BACHELOR OF ARTS (URBAN AND REGIONAL PLANNING, WITH IT) 	
	<p>BACHELOR OF SCIENCE(CONSTRUCTION MANAGEMENT) 	
	<p>DIPLOMA IN ARCHITECTURE 	
	<p>DIPLOMA IN QUANTITY SURVEYING 	
	<p>DIPLOMA IN BUILDING AND CIVIL ENGINEERING 	
	<p>DIPLOMA IN BUILDING AND CIVIL ENGINEERING 	
	<p>DIPLOMA IN CIVIL ENGINEERING 	
	<p>DIPLOMA IN ROAD TRANSPORT MANAGEMENT 	
	<p>DIPLOMA IN TRANSPORT MANAGEMENT 	
	<p>DIPLOMA IN CONSTRUCTION PLANT 	
	<p>DIPLOMA IN CONSTRUCTION PLANT ENGINEERING 	
	<p>DIPLOMA IN HIGHWAYS ENGINEERING 	
	<p>DIPLOMA IN ROAD CONSTRUCTION 	
	<p>Diploma Building Technology 	
	<p>DIPLOMA IN BUILDING 	
	<p>DIPLOMA IN BUILDING & CONSTRUCTION 	
	<p>DIPLOMA IN BUILDING CONSTRUCTION 	
	<p>DIPLOMA IN BUILDING CONSTRUCTION TECHNOLOGY 	
	<p>DIPLOMA IN BUILDING ENGINEERING TECHNOLOGY 	
	<p>DIPLOMA IN BUILDING TECHNOLOGY 	




</div>
<button class="accordion">BUSINESS AND COMMERCE/ACCOUNTING</button>
<div class="panel">
  
    <p>BACHELOR OF SCIENCE (MATHEMATICAL SCIENCES, WITH IT) 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS) 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS 	
	<p>BACHELOR OF COMMERCE 	
	<p>BACHELOR OF COMMERCE (B.COM) 	
	<p>BACHELOR OF COMMERCE(B.COM) 	
	<p>BACHELOR OF ECONOMICS 	
	<p>BACHELOR OF SCIENCE IN ECONOMICS 	
	<p>BACHELOR OF SCIENCE (RECORDS MANAGEMENT AND INFORMATION TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (PUBLIC ADMINISTRATION AND LEADERSHIP) 	
	<p>BACHELOR OF BUSINESS AND MANAGEMENT 	
	<p>BACHELOR OF BUSINESS MANAGEMENT 	
	<p>BACHELOR OF SECRETARIAL MANAGEMENT AND ADMINISTRATION 	
	<p>BACHELOR IN BUSINESS ADMINISTRATION 	
	<p>BACHELOR OF BUSINESS ADMINISTRATION 	
	<p>BACHELOR OF BUSINESS ADMINISTRATION ( WITH IT) 	
	<p>BACHELOR OF BUSINESS ADMINISTRATION WITH IT 	
	<p>BACHELOR OF BUSINESS AND OFFICE MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (TOURISM MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN TOURISM MANAGEMENT 	
	<p>BACHELOR OF TOURISM MANAGEMENT 	
	<p>BACHELOR OF BUSINESS ADMINISTRATION AND MANAGEMENT 
	<p>BACHELOR OF SCIENCE (AGRI BUSINESS MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS ECONOMICS AND FOOD INDUSTRY MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS MANAGEMENT & TRADE) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS MANAGEMENT, WITH IT) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE AGRIBUSINESS MANAGEMENT 	
	<p>BACHELOR OF SCIENCE(AGRIBUSINESS MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN AGRIBUSINESS MANGEMENT 	
	<p>BACHELOR OF HUMAN RESOURCE MANAGEMENT 	
	<p>BACHELOR OF HUMAN RESOURCES MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (HUMAN RESOURCE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE IN HUMAN REOURCE MANAGEMENT 	
	<p>BACHELOR OF ARTS (ECONOMICS & SOCIOLOGY) 	
	<p>BACHELOR OF ARTS (ECONOMICS AND SOCIOLOGY) 	
	<p>BACHELOR OF ECONOMICS & STATISTICS 	
	<p>BACHELOR OF ECONOMICS AND STATISTICS 	
	<p>BACHELOR OF SCIENCE (ECONOMICS & STATISTICS) 	
	<p>BACHELOR OF SCIENCE (ECONOMICS AND STATISTICS) 	
	<p>BACHELOR OF SCIENCE (BSC.) FLIGHT AND AVIATION BUSINESS MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION 	
	<p>BACHELOR OF SCIENCE (INNOVATION TECHNOLOGY MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE ( AGRICULTURAL ECONOMICS, WITH IT) 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL ECONOMICS 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL ECONOMICS) 	
	<p>BACHELOR OF SCIENCE IN AGRICULTURAL ECONOMICS 	
	<p>BACHELOR OF LIBRARY & INFORMATION SCIENCE 	
	<p>BACHELOR OF LIBRARY AND INFORMATION SCIENCE 	
	<p>BACHELOR OF LIBRARY AND INFORMATION STUDIES 	
	<p>BACHELOR OF SCIENCE (INFORMATION STUDIES) 	
	<p>BACHELOR OF SCIENCE IN LIBRARY AND INFORMATION SCIENCE 	
	<p>BACHELOR OF TECHNOLOGY (INFORMATION STUDIES) 	
	<p>BACHELOR OF TRAVEL & TOURS OPERATIONS MANAGEMENT 	
	<p>BACHELOR OF TRAVEL AND TOURS OPERATIONS MANAGEMENT 	
	<p>BACHELOR OF INTERNATIONAL TOURISM MANAGEMENT 	
	<p>BACHELOR OF PROCUREMENT AND CONTRACT MANAGEMENT 	
	<p>BACHELOR OF SUPPLY CHAIN MANAGEMENT 	
	<p>BACHELOR OF PURCHASING & SUPPLIES MANAGEMENT 	
	<p>BACHELOR OF PURCHASING AND SUPPLIES MANAGEMENT 	
	<p>BACHELOR OF LOGISTICS AND SUPPLY CHAIN MANAGEMENT 
	<p>BACHELOR OF PROCUREMENT AND SUPPLY CHAIN MANAGEMENT 	
	<p>BACHELOR PURCHASING AND SUPPLIES MANAGEMENT 	
	<p>BACHELOR OF PROCUREMENT AND LOGISTICS MANAGEMENT 	
	<p>BACHELOR OF PURCHASING AND SUPPLY CHAIN MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN AGRIBUSINESS MANAGEMENT AND MARKETING 	
	<p>BACHELOR OF AGRIBUSINESS MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN AGRIBUSINESS MANAGEMENT AND TRADE 	
	<p>BACHELOR OF ENTREPRENEURSHIP 	
	<p>BACHELOR OF ENTREPRENEURSHIP 	
	<p>BACHELOR OF SCIENCE (ENTREPRENEURSHIP AND SMALL ENTERPRISES MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (ENTREPRENEURSHIP) 	
	<p>BACHELOR OF SCIENCE IN ENTREPRENEURSHIP 	
	<p>BACHELOR OF ENTREPRENEURSHIP AND SMALL BUSINESS 	
	<p>BACHELOR OF ENTREPRENUERSHIP & SMALL BUSINESS MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (ENTREPRENEURSHIP STUDIES) 	
	<p>BACHELOR OF SCIENCE (ENTREPRENEURSHIP) 	
	<p>BACHELOR OF SCIENCE IN ENTREPRENEURSHIP 
	<p>BACHELOR OF REAL ESTATE 	
	<p>BACHELOR OF SCIENCE (REAL ESTATE) 	
	<p>BACHELOR OF TECHNOLOGY (REAL ESTATE AND PROPERTY MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (INDUSTRIAL MATHEMATICS) 	
	<p>BACHELOR OF PROJECT PLANNING AND MANAGEMENT 	
	<p>BACHELOR OF SCIENCE (PROJECT PLANNING AND MANAGEMENT) 
	<p>BACHELOR OF SCIENCE (PROJECT PLANNING MANAGEMENT) 
	<p>BACHELOR OF SCIENCE IN FINANCIAL ECONOMICS 	
	<p>BACHELOR OF ARTS (HISTORY & ECONOMICS) 	
	<p>BACHELOR OF ARTS (HISTORY AND ECONOMICS) 	
	<p>BA in Agricultural Economics and Agribusiness 	
	<p>BACHELOR OF COMMERCE IN MANAGEMENT INFORMATION SYSTEMS 	
	<p>BACHELOR OF BUSINESS LEADERSHIP 	
	<p>BACHELOR OF ARTS IN LEADERSHIP AND MANAGEMENT 	
	<p>BACHELOR OF LEADERSHIP AND MANAGEMENT 	
	<p>BACHELOR OF MANAGEMENT AND LEADERSHIP 	
	<p>BACHELOR OF SCIENCE (ACCOUNTANCY) 	
	<p>BACHELOR OF TECHNOLOGY (OFFICE ADMINISTRATION AND TECHNOLOGY) 	
	<p>BACHELOR OF ACCOUNTANCY AND FINANCIAL MANAGEMENT 	
	<p>BACHELOR OF TECHNOLOGY (INSTITUTIONAL CATERING AND ACCOMMODATION) 	
	<p>BACHELOR OF SCIENCE (EVENT AND CONVENTION MANAGEMENT) 	
	<p>BACHELOR OF TECHNOLOGY (APPLIED STATISTICS) 	
	<p>BACHELOR OF SCIENCE IN MANAGEMENT SCIENCE 	
	<p>BACHELOR OF BUSINESS MANAGEMENT (CIVIL AVIATION MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (STRATEGIC MANAGEMENT) 	
	<p>BACHELOR OF BUSINESS MANAGEMENT (MARINE BUSINESS MANAGEMENT) 	
	<p>BACHELOR OF CO-OPERATIVE MANAGEMENT 
	<p>BACHELOR OF CO-OPERATIVES AND COMMUNITY DEVELOPMENT 
	<p>BACHELOR OF SCIENCE (OPERATIONS RESEARCH) 	
	<p>BACHELOR OF SCIENCE (FINANCE) 	
	<p>BACHELOR OF ECONOMICS & FINANCE 	
	<p>BACHELOR OF ECONOMICS AND FINANCE 	
	<p>BACHELOR OF SCIENCE (FINANCE) 	
	<p>BACHELOR OF SCIENCE (HEALTH RECORDS & INFORMATION MGT.) 	
	<p>BACHELOR OF SCIENCE (HEALTH RECORDS AND INFORMATICS) 	
	<p>BACHELOR OF SCIENCE IN MARITIME MANAGEMENT (COMMERCIAL) 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS AND FINANCE 	
	<p>BACHELOR OF ARTS (BUSINESS STUDIES, WITH IT) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (AGRIBUSINESS) 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS & ECONOMICS, WITH IT 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS AND ECONOMICS) 	
	<p>BACHELOR OF SCIENCE IN ECONOMICS AND MATHEMATICS 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS & BUSINESS STUDIES, WITH IT) 	
	<p>BACHELOR OF CO-OPERATIVE BUSINESS 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL ECONOMICS AND RURAL DEVELOPMENT) 	
	<p>BACHELOR OF HEALTH SERVICES MANAGEMENT 	
	<p>BACHELOR OF ARTS (ECONOMICS,WITH IT) 	
	<p>BACHELOR OF ARTS (ECONOMICS) 
	<p>BACHELOR OF ARTS IN ECONOMICS 	
	<p>BACHELOR OF SCIENCE IN INTERNATIONAL BUSINESS ADMINISTRATION 	
	<p>BACHELOR OF BUSINESS INFORMATION AND MANAGEMENT 	
	<p>BACHELOR OF SCIENCE IN ACCOUNTING 	
	<p>BACHELOR OF SCIENCE IN HEALTH SYSTEMS MANAGEMENT 	2
	<p>BACHELOR OF SCIENCE IN FINANCE AND STATISTICS 	12
	<p>BACHELOR OF SCIENCE IN HEALTH INFORMATICS AND INFORMATION MANAGEMENT 	2
	<p>BACHELOR OF SCIENCE IN HEALTH RECORDS AND INFORMATION TECHNOLOGY 	9
	<p>BACHELOR OF SCIENCE IN REAL ESTATE MANAGEMENT 	12
	<p>BACHELOR OF SCIENCE IN TRAVEL AND TOURISM MANAGEMENT 	2
	<p>DIPLOMA IN CATERING & ACCOMMODATION MANAGEMENT 	
	<p>DIPLOMA IN CATERING AND ACCOMMODATION 	
	<p>DIPLOMA IN CATERING AND ACCOMMODATION MANAGEMENT 	
	<p>DIPLOMA IN CATERING AND HOTEL MANAGEMENT 	
	<p>BACHELOR OF SCIENCE AGRIBUSINESS MANAGEMENT AND ENTERPRISE DEVELOPMENT 	10
	<p>DIPLOMA IN MARKETING 	
	<p>DIPLOMA IN SALE AND MARKETING 	
	<p>DIPLOMA IN SALES & MARKETING 	
	<p>DIPLOMA IN SALES AND MARKETING 	
	<p>DIPLOMA IN ACCOUNTANCY 	
	<p>DIPLOMA IN ACCOUNTING & FINANCE 	
	<p>DIPLOMA IN PROJECT MANAGEMENT 	
	<p>DIPLOMA IN BANKING 	
	<p>DIPLOMA IN BANKING & FINANCE 	
	<p>DIPLOMA IN BANKING AND FINANCE 	
	<p>DIPLOMA IN IN SUPPLY CHAIN MANAGEMENT 	
	<p>DIPLOMA IN PURCHASING AND SUPPLIES MANAGEMENT 	
	<p>DIPLOMA IN SUPLILES CHAIN MANAGEMENT 	
	<p>DIPLOMA IN SUPPLIES AND CHAIN MANAGEMENT 	
	<p>DIPLOMA IN SUPPLIES CHAIN MANAGEMENT 	
	<p>DIPLOMA IN SUPPLY CHAIN MANAGEMENT 	
	<p>DIPLOMA IN SUPPLIES MANAGEMENT 	
	<p>DIPLOMA IN BUSINESS MANAGEMENT 	
	<p>DIPLOMA IN BUSINESS ADMINISTRATION 	
	<p>DIPLOMA IN BUSINESS ADMINISTRATION/MANAGEMENT 	
	<p>DIPLOMA IN LEADERSHIP AND MANAGEMENT 	
	<p>DIPLOMA IN APPLIED STATISTICS 	
	<p>DIPLOMA IN CREDIT MANAGEMENT 	
	<p>DIPLOMA IN HUMAN RESOURCE 	
	<p>DIPLOMA IN HUMAN RESOURCE MANAGEMENT 	
	<p>DIPLOMA IN PERSONNEL MANAGEMENT 	
	<p>DIPLOMA IN CO-OPERATIVE MANAGEMENT 	
	<p>DIPLOMA IN COOPERATIVE DEVELOPMENT 	
	<p>DIPLOMA IN COOPERATIVE MANAGEMENT 	
	<p>DIPLOMA IN SPORTS ADMINISTRATION AND MANAGEMENT 	
	<p>DIPLOMA IN MICRO-FINANCE 	
	<p>DIPLOMA IN LOGISTICS AND TRANSPORT MANAGEMENT 	
	<p>DIPLOMA IN PROCUREMENT AND MATERIALS MANAGEMENT 	
	<p>DIPLOMA IN SHIPPING 	
	<p>DIPLOMA IN AIR CARGO MANAGEMENT 	
	<p>DIPLOMA IN FLIGHT OPERATIONS/DISPATCH 	
	<p>DIPLOMA IN AIRPORT OPERATIONS 	
	<p>DIPLOMA IN ENTREPRENEURIAL AGRICULTURE 	
	<p>DIPLOMA IN ENTREPRENEURSHIP 	
	<p>DIPLOMA IN ENTREPRENEURSHIP DEVELOPMENT 	
	<p>DIPLOMA IN ENTREPRENEURSHIP EDUCATION 	
	<p>DIPLOMA IN AGRIBUSINESS MANAGEMENT 	





</div>
<button class="accordion">COMPUTER/IT/INFORMATION SCIENCE</button>
<div class="panel">
  

    <p>BACHELOR OF SCIENCE (COMPUTER SCIENCE 	
	<p>BACHELOR OF SCIENCE (COMPUTER SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN COMPUTER SCIENCE 	
	<p>BACHELOR OF INFORMATION COMMUNICATION TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (INFORMATION AND COMMUNICATION TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN INFORMATION & COMMUNICATION TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (STATISTICS & PROGRAMMING) 	
	<p>BACHELOR OF SCIENCE (STATISTICS) 	
	<p>BACHELOR OF SCIENCE IN STATISTICS 	
	<p>BACHELOR OF SCIENCE STATISTICS 	
	<p>BACHELOR OF SCIENCE ( APPLIED STATISTICS WITH COMPUTING) 	
	<p>BACHELOR OF SCIENCE (APPLIED STATISTICS WITH COMPUTING) 	
	<p>BACHELOR OF SCIENCE (APPLIED STATISTICS WITH PROGRAMMING) 	
	<p>BACHELOR OF SCIENCE (APPLIED STATISTICS, WITH IT) 	
	<p>BACHELOR OF SCIENCE (APPLIED STATISTICS) 	
	<p>BACHELOR OF SCIENCE IN APPLIED STATISTICS WITH COMPUTING 	
	<p>BACHELOR OF BUSINESS AND INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (COMPUTER TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN COMPUTER TECHNOLOGY 	
	<p>BACHELOR OF TECHNOLOGY (COMPUTER TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN COMPUTER AND ELECTRONIC SYSTEMS 	
	<p>BACHELOR OF INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (INFORMATION TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF TECHNOLOGY (INFORMATION TECHNOLOGY) 	
	<p>BACHELOR OF INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF TECHNOLOGY IN INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF BUSINESS INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF BUSINESS MANAGEMENT AND INFORMATION TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN INFORMATICS AND MATHEMATICS 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS & COMPUTER SCIENCE) 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS AND COMPUTER SCIENCE) 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS AND COMPUTING) 	
	<p>BACHELOR OF SCIENCE (MATHS AND COMPUTER SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS & COMPUTER SCIENCE 	
	<p>BACHELOR OF SCIENCE IN MATHEMATICS AND COMPUTER SCIENCE 	
	<p>BACHELOR OF SCIENCE ECONOMETRICS AND STATISTICS 	
	<p>BACHELOR OF TECHNOLOGY (BUSINESS INFORMATION TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (APPLIED COMPUTER SCIENCE) 	
	<p>BACHELOR OF SCIENCE IN APPLIED COMPUTER SCIENCE 	
	<p>BACHELOR OF SCIENCE (MATHEMATICS WITH IT) 	
	<p>BACHELOR OF SCIENCE (INFORMATICS ) 	
	<p>BACHELOR OF SCIENCE (INFORMATICS) 	
	<p>BACHELOR OF SCIENCE IN INFORMATICS 	
	<p>BACHELOR OF SCIENCE (BIOMETRY AND INFORMATICS) 	
	<p>BACHELOR OF SCIENCE IN NETWORKS AND COMMUNICATION SYSTEMS 	
	<p>BACHELOR OF TECHNOLOGY (COMMUNICATION AND COMPUTER NETWORKS) 	
	<p>BACHELOR OF SCIENCE (COMPUTER STUDIES) 	
	<p>BACHELOR OF SCIENCE IN APPLIED PHYSICS AND COMPUTER SCIENCE 	
	<p>BACHELOR OF TECHNOLOGY IN APPLIED PHYSICS (ELECTRONICS & INSTRUMENTATION) 	
	<p>BACHELOR OF SCIENCE (COMPUTER SECURITY AND FORENSICS) 
	<p>BACHELOR OF SCIENCE IN COMPUTER SECURITY AND FORENSICS 	
	<p>BACHELOR OF SCIENCE (BUSINESS COMPUTING) 	
	<p>BACHELOR OF SCIENCE(BUSINESS INFORMATION SYSTEMS) 	
	<p>BACHELOR OF MANAGEMENT INFORMATION SYSTEMS 	
	<p>BACHELOR OF SCIENCE IN COMPUTING AND INFORMATION SYSTEMS 	
	<p>BACHELOR OF SCIENCE IN APPLIED COMPUTER TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN INFORMATION SYSTEMS AND TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN COMPUTER INFORMATION SYSTEMS 
	<p>BACHELOR OF SCIENCE IN STATISTICS AND PROGRAMMING 	
	<p>BACHELOR OF SCIENCE IN JUSTICE INFORMATION SYSTEMS 	
	<p>BACHELOR OF SCIENCE IN STATISTICS & COMPUTER SCIENCE 	
	<p>DIPLOMA IN COMPUTER SCIENCE 	
	<p>DIPLOMA IN COMPUTER STUDIES 	
	<p>DIPLOMA IN BUSINESS INFORMATION TECHNOLOGY 	
	<p>DIPLOMA IN COMPUTER STUDIES 	
	<p>DIPLOMA IN INFORMATION TECHNOLOGY 	




</div>
<button class="accordion">EDUCATION</button>
<div class="panel">
  
    <p>BACHELOR OF EDUCATION (ARTS - GEO, MAT & BUS) 	
	<p>BACHELOR OF EDUCATION (ARTS, WITH IT) 	
	<p>BACHELOR OF EDUCATION (ARTS) 	
	<p>BACHELOR OF EDUCATION ARTS 	
	<p>BACHELOR OF EDUCATION(ARTS) WITH IT 	
	<p>BACHELOR OF EDUCATION (SCIENCE, WITH IT) 	
	<p>BACHELOR OF EDUCATION (SCIENCE) 	
	<p>BACHELOR OF EDUCATION(SCIENCE WITH IT) 	
	<p>BACHELOR OF EDUCATION (SPECIAL NEEDS EDUCATION, WITH IT) 	
	<p>BACHELOR OF EDUCATION (SPECIAL NEEDS EDUCATION) 	
	<p>BACHELOR OF EDUCATION IN SPECIAL EDUCATION 	
	<p>BACHELOR OF EDUCATION IN SPECIAL NEEDS EDUCATION 	
	<p>BACHELOR OF EDUCATION (ARTS) WITH SPECIAL NEEDS EDUCATION 	
	<p>BACHELOR OF EDUCATION (ARTS) MUSIC 	
	<p>BACHELOR OF EDUCATION (MUSIC, WITH IT) 	
	<p>BACHELOR OF MUSIC IN MUSIC EDUCATION 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD DEVELOPMENT) 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD EDUCATION, WITH IT) 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD EDUCATION) 	
	<p>BACHELOR OF EDUCATION IN EARLY CHILDHOOD EDUCATION 	
	<p>BACHELOR OF EDUCATION(EARLY CHILDHOOD DEVELOPMENT) 	
	<p>BACHELOR OF ARTS (WITH EDUCATION) 	
	<p>BACHELOR OF EDUCATION IN PRIMARY EDUCATION 	
	<p>BACHELOR OF SCIENCE IN HEALTH EDUCATION AND PROMOTION 	
	<p>BA in Church Educational Ministries 	
	<p>BA in Early Childhood Development Education 	
	<p>BACHELOR OF EDUCATION ARTS (HOME ECONOMICS) 	
	<p>BACHELOR OF EDUCATION (PHYSICAL EDUCATION) 	
	<p>BACHELOR OF EDUCATION (PHYSICAL EDUCATION AND SPORTS) 	
	<p>BACHELOR OF EDUCATION (ARTS) WITH GUIDANCE AND COUNSELLING 
	<p>BACHELOR OF EDUCATION (GUIDANCE AND COUNSELLING) 	
	<p>BACHELOR OF EDUCATION (TECHNOLOGY EDUCATION) 	
	<p>BACHELOR OF EDUCATION (TECHNOLOGY) 
	<p>BACHELOR OF EDUCATION (SCIENCE) WITH SPECIAL NEEDS EDUCATION 	
	<p>BACHELOR OF EDUCATION (SCIENCE) WITH GUIDANCE AND COUNSELING 	
	<p>BACHELOR OF EDUCATION (HOME SCIENCE AND TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE WITH EDUCATION 	
	<p>BACHELOR OF EDUCATION (ICT) 	
	<p>BACHELOR OF TECHNOLOGY EDUCATION (COMPUTER STUDIES) 	
	<p>BACHELOR OF EDUCATION (ARTS - BUSINESS STUDIES) 	
	<p>BACHELOR OF EDUCATION SCIENCE (COMPUTER) 	
	<p>BACHELOR OF EDUCATION (ARTS) FINE ART 	
	<p>BACHELOR OF ARTS (PEACE EDUCATION 	
	<p>BACHELOR OF EDUCATION (LIBRARY SCIENCE) 	
	<p>BACHELOR OF EDUCATION (SPECIAL NEEDS EDUCATION - PRIMARY OPTION) 	
	<p>BACHELOR OF EDUCATION SPECIAL NEEDS EDUCATION PRIMARY OPTION 	
	<p>BACHELOR OF EDUCATION (SPECIAL NEEDS EDUCATION - SECONDARY OPTION) 	
	<p>BACHELOR OF EDUCATION SPECIAL NEEDS EDUCATION SECONDARY OPTION 	
	<p>BACHELOR OF EDUCATION IN EARLY CHILDHOOD STUDIES 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD & PRIMARY EDUCATION) 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD AND PRIMARY EDUCATION) 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD DEVELOPMENT EDUCATION) 	
	<p>BACHELOR OF EDUCATION (EARLY CHILDHOOD) 	
	<p>DIPLOMA IN TEACHER EDUCATION (BIOLOGY / CHEMISTRY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (BIOLOGY/MATHEMATICS) 	
	<p>DIPLOMA IN TEACHER EDUCATION (CHEMISTRY/MATHEMATICS) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GEOGRAPHY/CHRISTIAN RELIGIOUS EDUCATION) 	
	<p>DIPLOMA IN TEACHER EDUCATION (PHYSICS/CHEMISTRY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ARABIC/IRE OR ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GERMAN/ ENGLISH OR C.R.E OR HISTORY OR GEOGRAPHY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MUSIC/ENGLISH OR KISWAHILI) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ART AND DESIGN / ENGLISH OR KISWAHILI) 	
	<p>DIPLOMA IN HEALTH PROMOTION AND EDUCATION 	
	<p>DIPLOMA IN TEACHER EDUCATION (ENGLISH / CRE) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ENGLISH AND CHRISTIAN RELIGIOUS EDUCATION) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ENGLISH / HISTORY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ENGLISH AND HISTORY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (FRENCH WITH EITHER HISTORY, GEOGRAPHY, CRE, IRE OR ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (FRENCH/GEOGRAPHY OR HISTORY OR C.R.E OR ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (KISWAHILI / HISTORY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (KISWAHILI/HISTORY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MATHEMATICS/COMPUTER STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MATHEMATICS/COMPUTER) 	
	<p>DIPLOMA IN TEACHER EDUCATION (PHYSICS/COMPUTER) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ISLAMIC RELIGIOUS EDUCATION WITH EITHER ARABIC/KISWAHILI/GEOGRAPHY/ENGLISH/HISTORY ) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ISLAMIC RELIGIOUS STUDIES/ENGLISH OR KISWAHILI OR HISTORY OR GEOGRAPHY 	
	<p>DIPLOMA IN TEACHER EDUCATION (HISTORY / CRE) 	
	<p>DIPLOMA IN TEACHER EDUCATION (HISTORY WITH CHRISTIAN RELIGIOUS EDUCATION) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MATHEMATICS / BUSINESS STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MATHEMATICS/BUSINESS STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (KISWAHILI / GEOGRAPHY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (KISWAHILI/GEOGRAPHY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GEOGRAPHY / BUSINESS STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GEOGRAPHY/BUSINESS STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (PHYSICS/MATHEMATICS) 	
	<p>DIPLOMA IN TEACHER EDUCATION (AGRICULTURE/BIOLOGY) 	
	<p>DIPLOMA IN TEACHER EDUCATION ( KISWAHILI / CHRISTIAN RELIGIOUS EDUCATION) 	
	<p>DIPLOMA IN TEACHER EDUCATION ( KISWAHILI / CRE) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ENGLISH AND GEOGRAPHY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GEOGRAPHY/ HISTORY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MATHS / GEOGRAPHY) 	
	<p>DIPLOMA IN TEACHER EDUCATION (GERMAN/ ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MUSIC/ENGLISH ) 	
	<p>DIPLOMA IN TEACHER EDUCATION (MUSIC/KISWAHILI) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ART AND DESIGN / ENGLISH ) 	
	<p>DIPLOMA IN TEACHER EDUCATION (ART AND DESIGN / KISWAHILI) 	
	<p>DIPLOMA IN TEACHER EDUCATION (FRENCH/ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (IRE WITH ARABIC) 	
	<p>DIPLOMA IN TEACHER EDUCATION (IRE WITH ENGLISH) 	
	<p>DIPLOMA IN TEACHER EDUCATION (PHYSICS / COMPUTER STUDIES) 	
	<p>DIPLOMA IN TEACHER EDUCATION (AGRICULTURE / CHEMISTRY) 	






</div>
<button class="accordion">ENGINEERING</button>
<div class="panel">
  


	<p>BACHELOR OF SCIENCE (INDUSTRIAL CHEMISTRY, WITH IT) 	
	<p>BACHELOR OF SCIENCE (INDUSTRIAL CHEMISTRY) 	
	<p>BACHELOR OF SCIENCE IN INDUSTRIAL CHEMISTRY 	
	<p>BACHELOR OF SCIENCE (ANALYTICAL CHEMISTRY WITH MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (ANALYTICAL CHEMISTRY) 	
	<p>BACHELOR OF SCIENCE IN ANALYTICAL CHEMISTRY 	
	<p>BACHELOR OF SCIENCE IN ANALYTICAL CHEMISTRY WITH COMPUTING 	
	<p>BACHELOR OF ENGINEERING (CIVIL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (CIVIL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE CIVIL ENGINEERING 	
	<p>BACHELOR OF SCIENCE IN CIVIL ENGINEERING 	
	<p>BACHELOR OF SCIENCE (ELECTRICAL & ELECTRONICS ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (ELECTRICAL AND ELECTRONIC ENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN ELECTRICAL & ELECTRONIC ENGINEERING 	
	<p>BACHELOR OF SCIENCE IN ELECTRICAL AND ELECTRONIC ENGINEERING 	
	<p>BACHELOR OF SCIENCE IN ELECTRICAL AND ELECTRONICS ENGINEERING 	
	<p>BACHELOR OF ENGINEERING (MECHANICAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (MECHANICAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN MECHANICAL ENGINEERING 	
	<p>BACHELOR OF ENGINEERING (GEOSPATIAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (GEOSPATIAL ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (AGRICULTURAL & BIO-SYSTEMS ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL & BIO-SYSTEMS ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL AND BIOSYSTEMS ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (AGRICULTURAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (BIOSYSTEMS ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (MICROPROCESSOR TECHNOLOGY AND INSTRUMENTATION) 	
	<p>BACHELOR OF SCIENCE (MARINE ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (PHYSICS) 	
	<p>BACHELOR OF SCIENCE (WATER AND ENVIRONMENTAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (TELECOMMUNICATION & INFORM. TECH) 	
	<p>BACHELOR OF SCIENCE (TELECOMMUNICATION AND INFORMATION ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (MANUFACTURING ENGINEERING & TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN MECHANICAL AND MANUFACTURING ENGINEERING 	
	<p>BACHELOR OF SCIENCE IN PETROLEUM EXPLORATION AND PRODUCTION 	
	<p>BACHELOR OF SCIENCE (INSTRUMENTATION & CONTROL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (CONTROL AND INSTRUMENTATION) 	
	<p>BACHELOR OF SCIENCE (MECHATRONIC ENGINEERING) 
	<p>BACHELOR OF SCIENCE IN MECHATRONIC ENGINEERING 	
	<p>BACHELOR OF SCIENCE (ELECTRICAL AND COMMUNICATION ENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN ELECTRICAL AND TELECOMMUNICATION ENGINEERING 	
	<p>BACHELOR OF SCIENCE (MECHANICAL AND INDUSTRIAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN TECHNOLOGY (AUTOMOTIVE) 	
	<p>BACHELOR OF EDUCATION IN TECHNOLOGY (MECHANICAL ENGINEERING) 	
	<p>BACHELOR OF EDUCATION IN TECHNOLOGY (ELECTRICAL & ELECTRONIC ENGINEERING) 	
	<p>BACHELOR OF EDUCATION IN TECHNOLOGY (CIVIL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (MINING & MINERAL PROCESSING ENGINEERING) 	
    <p>BACHELOR OF SCIENCE (MINING AND MINERAL PROCESSING ENGINEERING) 	
    <p>BACHELOR OF SCIENCE (ELECTRONIC AND COMPUTER ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (FINANCIAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (PHYSICS WITH APPROPRIATE TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY (TECHNICAL AND APPLIED PHYSICS) 	
	<p>BACHELOR OF TECHNOLOGY (INDUSTRIAL AND APPLIED CHEMISTRY) 	
	<p>BACHELOR OF TECHNOLOGY IN APPLIED CHEMISTRY (ANALYTICAL & INDUSTRIAL OPTIONS) 	
	<p>BACHELOR OF SCIENCE (ELECTRONICS) 	
	<p>BACHELOR OF ENGINEERING (AERONAUTICAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (NUTRACEUTICAL SCIENCE AND TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN ELECTRONICS 	
	<p>BACHELOR OF SCIENCE (INDUSTRIAL CHEMISTRY WITH MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (CHEMISTRY) 	
	<p>BACHELOR OF SCIENCE CHEMISTRY ( INORGANIC, PHYSICAL AND ORGANIC OPTIONS) 	
	<p>BACHELOR OF SCIENCE IN CHEMISTRY 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY) 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY AND BIO-FUELS TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY AND BIOFUELS TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN RENEWABLE ENERGY & ENVIRONMENTAL PHYSICS 	
	<p>BACHELOR OF TECHNOLOGY (ELECTRICAL AND ELECTRONIC ENGINEERING TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN ELECTRICAL AND ELECTRONIC ENGINEERING 	
	<p>BACHELOR OF TECHNOLOGY (CIVIL ENGINEERING TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN CIVIL ENGINEERING 	
	<p>BACHELOR OF TECHNOLOGY IN MEDICAL ENGINEERING 	
	<p>BACHELOR OF TECHNOLOGY (MECHANICAL ENGINEERING TECHNOLOGY) 	
	<p>BACHELOR OF TECHNOLOGY IN MECHANICAL ENGINEERING 	
	<p>BACHELOR OF TECHNOLOGY IN MARINE ENGINEERING 	
	<p>BACHELOR OF SCIENCE IN SOFTWARE ENGINEERING 	
	<p>BACHELOR OF SCIENCE (APPLIED BIOENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN APPLIED OPTICS AND LASERS 	
	<p>BACHELOR OF SCIENCE (PETROLEUM ENGINEERING) 
	<p>BACHELOR OF SCIENCE(AEROSPACE ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (PETROLEUM CHEMISTRY) 	
	<p>BACHELOR OF ENGINEERING (CHEMICAL AND PROCESS ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (CHEMICAL ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (INDUSTRIAL AND TEXTILE ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (CIVIL & STRUCTURAL ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (CIVIL AND STRUCTURAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (CIVIL AND STRUCTURAL ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (ELECTRICAL AND ELECTRONIC ENGINEERING) 
	<p>BACHELOR OF ENGINEERING (ELECTRICAL AND ELECTRONICS ENGINEERING) 	
	<p>BACHELOR OF SCIENCES (MECHANICAL & MANUFACTURING ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (ENERGY TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (ENERGY ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY TECHNOLOGY AND MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY AND TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN RENEWABLE ENERGY AND TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE (BIOMEDICAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE (MEDICAL ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (ELECTRICAL AND TELECOMMUNICATION ENGINEERING) 	
	<p>BACHELOR OF TECHNOLOGY (CHEMICAL ENGINEERING) 	
	<p>BACHELOR OF SCIENCE IN TELECOMMUNICATIONS 	
	<p>BACHELOR OF ENGINEERING (MECHANICAL & PRODUCTION ENGINEERING) 	
	<p>BACHELOR OF ENGINEERING (MECHANICAL AND PRODUCTION ENGINEERING) 	
	<p>DIPLOMA IN CIVIL ENGINEERING TECHNOLOGY 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (ELECTRONICS OPTION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS 	
	<p>DIPLOMA IN AUTOMOTIVE ENGINEERING 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING ( PLANT) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (PLANT OPTION) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (PLANT) 	
	<p>DIPLOMA IN ELCTRICAL ENGINEERING (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING (TELECOMMUNICATION OPTION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING (TELECOMMUNICATIONS) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (TELECOMMUNICATION Option) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL ELECTRONICS (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL ENGINEERING (TELECOMMUNICATION) 	
	<p>DIPLOMA IN ELECTRICAL/ ELECTRONICS TECHNOLOGY (TELECOMMUNICATION) 	
	<p>DIPLOMA IN TELECOMMUNICATION ENGINEERING 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS 	
	<p>DIPLOMA IN ELECTRONICS 	
	<p>DIPLOMA IN ELECTRONICS ENGINEERING 	
	<p>DIPLOMA IN MECHATRONICS 	
	<p>DIPLOMA IN MEDICAL ENGINEERING 	
	<p>DIPLOMA IN CHEMICAL ENGINEERING 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING TECHNOLOGY 	
	<p>DIPLOMA IN POWER AND PROCESS ENGINEERING 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (PRODUCTION OPTION) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (PRODUCTION) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING(PRODUCTION OPTION) 	
	<p>DIPLOMA IN ELECTRICAL (INSTRUMENTATION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (CONTROL & INSTRUMENTATION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONIC (CONTROL) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS (INSTRUMENTATION & CONTROL) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS (INSTRUMENTATION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS ENGINEERING (INSTRUMENTATION) 	
	<p>DIPLOMA IN ELECTRICAL ELECTRONICS (INSTRUMENTATION) 	
	<p>DIPLOMA IN MOTOR VEHICLE MECHANICS 	
	<p>DIPLOMA IN MARINE ENGINEERING 	
	<p>DIPLOMA IN TECHNOLOGY MEDICAL ENGINEERING 	
	<p>DIPLOMA IN TECHNOLOGY IN (ELECTRONICS & AUTOMATION ENGINEERING) 	
	<p>DIPLOMA IN TECHNOLOGY IN ELECTRONIC ENGINEERING 	
	<p>DIPLOMA IN TECHNOLOGY IN ELECTRICAL POWER ENGINEERING 	
	<p>DIPLOMA IN TECHNOLOGY (INSTRUMENTATION & CONTROL) 	
	<p>DIPLOMA IN TECHNOLOGY (TELECOMMUNICATION & INFORMATION ENGINEERING) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (AUTOMOTIVE OPTION) 	
	<p>DIPLOMA IN MECHANICAL ENGINEERING (AUTOMOTIVE) 	
    <p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING (POWER OPTION) 	
	<p>DIPLOMA IN ELCTRICAL ENGINEERING (POWER) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING (POWER) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING(POWER OPTION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONIC ENGINEERING(POWER) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS (POWER) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (POWER OPTION) 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS ENGINEERING (POWER) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS (POWER OPTION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS (POWER) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS ENGINEERING 	
	<p>Diploma in Electrical and Electronics Engineering (Power option) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS ENGINEERING (POWER) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS ENGINEERING(POWER) 	
	<p>DIPLOMA IN ELECTRICAL ELECTRONICS (POWER) 	
	<p>DIPLOMA IN ELECTRICAL ENGINEERING (POWER OPTION) 	
	<p>DIPLOMA IN ELECTRICAL ENGINEERING (POWER) 	
	<p>DIPLOMA IN ELECTRICAL ENGINEERING(POWER) 	
	<p>DIPLOMA IN ELECTRICAL/ELECTRONIC ENGINEERING (POWER) 	
	<p>DIPLOMA IN REFRACTION TECHNOLOGY 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS TECHNOLOGY 	
	<p>DIPLOMA IN ELECTRICAL & ELECTRONICS TECHNOLOGY (POWER) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONIC TECHNOLOGY (POWER OPTION) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS TECHNOLOGY (POWER) 	
	<p>DIPLOMA IN ELECTRICAL AND ELECTRONICS TECHNOLOGY (TELECOMMUNICATION) 	
	<p>DIPLOMA IN AERONAUTICAL ENGINEERING (AVIONICS) 	
	<p>DIPLOMA IN AERONAUTICAL ENGINEERING (AIRFRAMES AND ENGINES) 	
	<p>DIPLOMA IN PETROLEUM AND GEOSCIENCE 	
	<p>DIPLOMA IN PETROLEUM MANAGEMENT 	
	<p>DIPLOMA IN OPTHALMIC TECHNOLOGY 	







</div>
<button class="accordion">ENVIRONMENTAL SCIENCE</button>
<div class="panel">
  
    <p>BACHELOR OF SCIENCE (ENVIRONMENTAL CONSERVATION AND NATURAL RESOURCES MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENTAL HEALTH) 	
	<p>BACHELOR OF SCIENCE IN ENVIRONMENTAL HEALTH 	
	<p>BACHELOR OF ENVIRONMENTAL SCIENCE 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (SCIENCE) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENTAL SCIENCE, WITH IT) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENTAL SCIENCE) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENTAL SCIENCES) 	
	<p>BACHELOR OF SCIENCE IN ENVIRONMENTAL SCIENCE 	
	<p>BACHELOR OF SCIENCE IN ENVIRONMENTAL STUDIES 	
	<p>BACHELOR OF SCIENCE(ENVIRONMENTAL STUDIES) 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (ARTS) 	
	<p>BACHELOR OF ARTS IN ENVIRONMENTAL PLANNING AND MANAGEMENT 	
	<p>BACHELOR OF ENVIRONMENTAL PLANNING & MANAGEMENT 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (BIOLOGY AND HEALTH) 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (EARTH SCIENCES) 	
	<p>BACHELOR OF TECHNOLOGY (ENVIRONMENTAL RESOURCE MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (WATER RESOURCES AND ENVIRONMENT) 	
	<p>BACHELOR OF SCIENCE (WATER AND ENVIRONMENT MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (RENEWABLE ENERGY AND ENVIRONMENTAL PHYSICS) 	
	<p>BACHELOR OF SCIENCE IN ENERGY AND ENVIRONMENTAL TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN ENVIRONMENTAL HEALTH SCIENCES (PUBLIC HEALTH) 	
	<p>BACHELOR OF ENVIRONMENTAL EDUCATION 	
	<p>BACHELOR OF SCIENCE ( ENVIRONMENTAL CHEMISTRY) 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (ENVIRONMENTAL RESOURCE CONSERVATION) 	
	<p>BACHELOR OF SCIENCE ( ENVIRONMENTAL MANAGEMENT AND CONSERVATION) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENT MANAGEMENT AND CONSERVATION) 	
	<p>BACHELOR OF SCIENCE (DISASTER PREPAREDNESS AND ENVIRONMENT TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (ENVIRONMENTAL MANAGEMENT) 	
	<p>BACHELOR OF ENVIRONMENTAL STUDIES (COMMUNITY RESOURCE CONSERVATION) 	
	<p>BACHELOR OF SCIENCE (COMMUNITY RESOURCE MANAGEMENT) 	
	<p>DIPLOMA IN ENVIRONMENTAL MANAGEMENT 	
	<p>DIPLOMA IN ENVIRONMENTAL SCIENCE 	
	<p>DIPLOMA IN ENVIRONMENTAL SCIENCES 	
	<p>DIPLOMA IN ENVIROMENTAL HEALTH SCIENCES 	





</div>
<button class="accordion">FOOD SCIENCE AND TECHNOLOGY</button>
<div class="panel">
 
 	<p>BACHELOR OF SCIENCE (FOOD SCIENCE & TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (FOOD SCIENCE AND TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE IN FOOD SCIENCE AND TECHNOLOGY 	
	<p>BACHELOR OF SCIENCE IN FOOD TECHNOLOGY & QUALITY ASSURANCE 	
	<p>BACHELOR OF TECHNOLOGY (FOOD SCIENCE AND TECHNOLOGY) 	
	<p>BACHELOR OF SCIENCE (FOOD NUTRITION & DIETETICS) 	
	<p>BACHELOR OF SCIENCE (FOOD NUTRITION AND DIETETICS) 	
	<p>BACHELOR OF SCIENCE (FOOD, NUTRITION & DIETETICS) 	
	<p>BACHELOR OF SCIENCE (NUTRITION AND DIETETICS, WITH IT) 	
	<p>BACHELOR OF SCIENCE IN FOOD NUTRITION AND DIETETICS 	
	<p>BACHELOR OF SCIENCE (FOOD SCIENCE & NUTRITION) 	
	<p>BACHELOR OF SCIENCE (FOOD SCIENCE AND NUTRITION) 	
	<p>BACHELOR OF SCIENCE IN FOOD SCIENCE AND NUTRITION 	
	<p>BACHELOR OF SCIENCE IN FOODS AND NUTRITION 	
	<p>BACHELOR OF SCIENCE IN NUTRITION AND DIETETICS 	
	<p>BACHELOR OF SCIENCE (FOOD SCIENCE AND NUTRITION) 	
	<p>BACHELOR OF TECHNOLOGY (NUTRITION AND DIETETICS) 	
	<p>BACHELOR OF SCIENCE (HUMAN NUTRITION AND DIETETICS) 	
	<p>BACHELOR OF SCIENCE IN HUMAN NUTRITION AND DIETETICS 	
	<p>BACHELOR OF SCIENCE(FOOD SECURITY) 	
	<p>BACHELOR OF SCIENCE IN FOOD SCIENCE AND PROCESSING 	
	<p>BACHELOR OF SCIENCE (FOOD SCIENCE AND MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (FOOD PROCESSING TECHNOLOGY ) 	
	<p>BACHELOR OF SCIENCE (FOOD OPERATIONS MANAGEMENT) 	
	<p>BACHELOR OF SCIENCE (FOOD SERVICE AND HOSPITALITY MANAGEMENT) 	
	<p>DIPLOMA IN FOOD & BEVERAGE 	
	<p>DIPLOMA IN FOOD & BEVERAGE MANAGEMENT 	
	<p>DIPLOMA IN FOOD & BEVERAGE PROD,SALES & SERVICES MANAGEMENT 	
	<p>DIPLOMA IN FOOD & BEVERAGE PRODUCTION & SALES SERVICES 	
	<p>DIPLOMA IN FOOD & BEVERAGE PRODUCTION, SALES & SERVICE 	
	<p>DIPLOMA IN FOOD & BEVERAGE PRODUCTION,SALES & SERVICE MANAGEMENT 	
	<p>DIPLOMA IN FOOD & BEVERAGES PRODUCTION 	
	<p>DIPLOMA IN FOOD & BEVERAGES PRODUCTION,SALES &SERVICE MGT. 	
	<p>DIPLOMA IN FOOD AND BEVERAGE 	
	<p>DIPLOMA IN FOOD AND BEVERAGE MANAGEMENT 	
	<p>DIPLOMA IN FOOD AND BEVERAGE PRODUCTION AND SERVICE MANAGEMENT 	
	<p>DIPLOMA IN FOOD AND BEVERAGE PRODUCTION,SALES AND SERVICES 	
	<p>DIPLOMA IN FOOD AND BEVERAGE,PRODUCTION AND SERVICE 	
	<p>DIPLOMA IN FOOD AND BEVERAGE(PRODUCTION AND SERVICE) 	
	<p>DIPLOMA IN FOOD AND BEVERAGES 	
	<p>DIPLOMA IN FOOD AND BEVERAGES PRODUCTION, SALES & SERVICE MANAGEMENT. 	
	<p>DIPLOMA IN COMMUNITY HEALTH AND NUTRITION 	
	<p>DIPLOMA IN FOOD SCIENCE AND TECHNOLOGY 	
	<p>DIPLOMA IN FOOD SCIENCE TECHNOLOGY 	
	<p>DIPLOMA IN FOOD TECHNOLOGY 	
	<p>DIPLOMA IN INFORMATION & COMMUNICATION TECHNOLOGY 	
	<p>DIPLOMA IN INFORMATION COMMUNICATION TECHNOLOGY 	
	<p>DIPLOMA IN INFORMATION COMMUNICATION TECHNOLOGY (ICT) 	
	<p>DIPLOMA IN INFORMATION COMMUNICATION TECHNOLOGY(ICT) 	
	<p>DIPLOMA INFORMATION COMMUNICATION TECHNOLOGY 	
	<p>DIPLOMA IN COMMUNITY NUTRITION 	
	<p>DIPLOMA IN DIETETIC MANAGEMENT 	
	<p>DIPLOMA IN DIETETICS MANAGEMENT 	
	<p>DIPLOMA IN NUTRITION AND DIET MANAGEMENT 	
	<p>DIPLOMA IN NUTRITION 	
	<p>DIPLOMA IN NUTRITION & DIETETIC MANAGEMENT 	
	<p>DIPLOMA IN NUTRITION & DIETETICS 	
	<p>DIPLOMA IN FOOD TECHNOLOGY & QUALITY ASSURANCE 	




</div>










<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  }
}
</script>

</body>